## Did we store any non-standard ISO level 2/3 area codes?

In [1]:
from init import *

Populating the interactive namespace from numpy and matplotlib

In [2]:
df = pd.read_feather("intermediate/01-countries-from-mysql.feather")

In [3]:
df

,id,owid_name,iso_alpha2,iso_alpha3,imf_code,cow_letter,cow_code,unctad_code,marc_code,ncd_code,kansas_code,penn_code,continent
0,562,Afghanistan,AF,AFG,512.0,AFG,700.0,AFG,AF,AFGN,AFG,AFG,2.0
1,791,Aland Islands,AX,ALA,NaN,None,NaN,None,None,None,None,None,4.0
2,565,Albania,AL,ALB,914.0,ALB,339.0,ALB,AA,ALBN,ALB,ALB,4.0
3,619,Algeria,DZ,DZA,612.0,ALG,615.0,ALG,AE,ALGR,DZA,DZA,3.0
4,571,American Samoa,AS,ASM,859.0,None,NaN,None,AS,None,ASM,ASM,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,830,Yemen Arab Republic,None,None,NaN,YAR,678.0,None,None,None,None,None,2.0
276,831,Yemen People's Republic,None,None,NaN,YPR,680.0,None,None,None,None,None,2.0
277,789,Zambia,ZM,ZMB,754.0,ZAM,551.0,ZAM,ZA,ZMBA,ZMB,ZMB,3.0
278,829,Zanzibar,None,None,NaN,ZAN,511.0,None,None,None,None,None,3.0
279,790,Zimbabwe,ZW,ZWE,698.0,ZIM,552.0,ZIM,RH,ZIMB,ZWE,ZWE,3.0

### What entities do not have iso alpha 2 codes?

In [4]:
df[df["iso_alpha2"].isnull()]

,id,owid_name,iso_alpha2,iso_alpha3,imf_code,cow_letter,cow_code,unctad_code,marc_code,ncd_code,kansas_code,penn_code,continent
15,822,Austria-Hungary,None,None,NaN,AUH,300.0,None,None,None,None,None,4.0
17,816,Baden,None,None,NaN,BAD,267.0,None,None,None,None,None,4.0
22,813,Bavaria,None,None,NaN,BAV,245.0,None,None,None,None,None,4.0
45,837,Caribbean Netherlands,None,None,NaN,None,NaN,None,None,None,None,None,5.0
49,834,Channel Islands,None,None,NaN,None,NaN,None,None,None,None,None,4.0
65,823,Czechoslovakia,None,None,NaN,CZE,315.0,None,None,None,None,None,4.0
71,815,East Germany,None,None,NaN,GDR,265.0,None,None,None,None,None,4.0
105,812,Hanover,None,None,NaN,HAN,240.0,None,None,None,None,None,4.0
107,819,Hesse Electoral,None,None,NaN,HSE,273.0,None,None,None,None,None,4.0
108,820,Hesse Grand Ducal,None,None,NaN,HSG,275.0,None,None,None,None,None,4.0
128,832,Korea,None,None,NaN,KOR,730.0,None,None,None,None,None,2.0
129,828,Kosovo,None,None,NaN,KOS,347.0,None,None,None,None,None,4.0
153,821,Mecklenburg Schwerin,None,None,NaN,MEC,280.0,None,None,None,None,None,4.0
154,835,Melanesia,None,None,NaN,None,NaN,None,None,None,None,None,6.0
157,632,Micronesia (region),None,None,NaN,None,NaN,None,None,None,None,None,NaN
158,825,Modena,None,None,NaN,MOD,332.0,None,None,None,None,None,4.0
181,838,Northern Cyprus,None,None,NaN,None,NaN,None,None,None,None,None,4.0
191,826,Parma,None,None,NaN,PMA,335.0,None,None,None,None,None,4.0
196,836,Polynesia,None,None,NaN,None,NaN,None,None,None,None,None,6.0
200,833,Republic of Vietnam,None,None,NaN,RVN,817.0,None,None,None,None,None,2.0
201,560,Rest of the World,None,None,NaN,None,NaN,None,None,None,None,None,NaN
217,817,Saxony,None,None,NaN,SAX,269.0,None,None,None,None,None,4.0
253,827,Tuscany,None,None,NaN,TUS,337.0,None,None,None,None,None,4.0
255,824,Two Sicilies,None,None,NaN,SIC,329.0,None,None,None,None,None,4.0
270,814,West Germany,None,None,NaN,GFR,260.0,None,None,None,None,None,4.0
272,559,World,None,None,NaN,None,NaN,None,None,None,None,None,NaN
273,818,Wuerttemburg,None,None,NaN,WRT,271.0,None,None,None,None,None,4.0
275,830,Yemen Arab Republic,None,None,NaN,YAR,678.0,None,None,None,None,None,2.0
276,831,Yemen People's Republic,None,None,NaN,YPR,680.0,None,None,None,None,None,2.0
278,829,Zanzibar,None,None,NaN,ZAN,511.0,None,None,None,None,None,3.0

ðŸ’¡ This looks like most of these are historical entities. World is the main entitiy that we might want to have that does not have a ISO Alpha 2 code